import pandas as pd
import os

# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(BASE_DIR, "01_data", "processed", "clean_biometric_data.csv")

def check_locations():
    if not os.path.exists(DATA_PATH):
        print(f"Data file not found at {DATA_PATH}")
        return

    print(f"Loading data from {DATA_PATH}...")
    try:
        data = pd.read_csv(DATA_PATH, low_memory=False)
    except Exception as e:
        print(f"Error reading CSV: {e}")
        return

    # --- DATA CLEANING (COPIED FROM model_service.py) ---
    
    # Standardize State Case
    if 'state' in data.columns:
        data['state'] = data['state'].astype(str).str.title().str.strip()
        
        state_corrections = {
            'Andaman & Nicobar Islands': 'Andaman and Nicobar Islands',
            'Andaman And Nicobar Islands': 'Andaman and Nicobar Islands',
            'Chhatisgarh': 'Chhattisgarh',
            'Dadra & Nagar Haveli': 'Dadra and Nagar Haveli and Daman and Diu',
            'Dadra And Nagar Haveli': 'Dadra and Nagar Haveli and Daman and Diu',
            'Daman & Diu': 'Dadra and Nagar Haveli and Daman and Diu',
            'Daman And Diu': 'Dadra and Nagar Haveli and Daman and Diu',
            'Jammu & Kashmir': 'Jammu and Kashmir',
            'Jammu And Kashmir': 'Jammu and Kashmir',
            'Orissa': 'Odisha',
            'Pondicherry': 'Puducherry',
            'Tamilnadu': 'Tamil Nadu',
            'Uttaranchal': 'Uttarakhand', 
            'Delhi': 'Delhi', 
            'Nct Of Delhi': 'Delhi',
            'West Bangal': 'West Bengal',
            'Westbengal': 'West Bengal',
            'West  Bengal': 'West Bengal',
            'Telengana': 'Telangana'
        }
        data['state'] = data['state'].replace(state_corrections)

    # Normalize Districts
    if 'district' in data.columns:
        data['district'] = data['district'].astype(str).str.title().str.strip()
        
        district_corrections = {
            'Ahmadabad': 'Ahmedabad',
            'Ahmednagar': 'Ahmednagar',
            'Almora': 'Almora',
            'Amrawati': 'Amravati',
            'Amritsar': 'Amritsar',
            'Anugul': 'Angul',
            'Ariyalur': 'Ariyalur',
            'Badgam': 'Budgam',
            'Bagalkot': 'Bagalkot',
            'Bageshwar': 'Bageshwar',
            'Bahraich': 'Bahraich',
            'Balaghat': 'Balaghat',
            'Baleshwar': 'Balasore',
            'Ballia': 'Ballia',
            'Banaskantha': 'Banaskantha',
            'Bandipora': 'Bandipora',
            'Bangalore': 'Bangalore', # or Bengaluru
            'Bangalore Rural': 'Bangalore Rural',
            'Bangalore Urban': 'Bangalore Urban',
            'Bankura': 'Bankura',
            'Bara Banki': 'Barabanki',
            'Baramula': 'Baramulla',
            'Barwani': 'Barwani',
            'Baudh': 'Boudh',
            'Belgaum': 'Belgaum',
            'Bellary': 'Ballari',
            'Bemetara': 'Bemetara',
            'Bidar': 'Bidar',
            'Bijapur': 'Vijayapura', # KARNATAKA
            # Note: Chhattisgarh also has Bijapur. Context matters but simple map hits both?
            'Bilaspur': 'Bilaspur',
            'Birbhum': 'Birbhum',
            'Bishnupur': 'Bishnupur',
            'Bokaro': 'Bokaro',
            'Bongaigaon': 'Bongaigaon',
            'Bulandshahr': 'Bulandshahr',
            'Buldana': 'Buldhana',
            'Bundi': 'Bundi',
            'Burhanpur': 'Burhanpur',
            'Cachar': 'Cachar',
            'Chamarajanagar': 'Chamarajanagar',
            'Chamba': 'Chamba',
            'Chamoli': 'Chamoli',
            'Champawat': 'Champawat',
            'Champhai': 'Champhai',
            'Chandauli': 'Chandauli',
            'Chandel': 'Chandel',
            'Chandigarh': 'Chandigarh',
            'Chandrapur': 'Chandrapur',
            'Changlang': 'Changlang',
            'Chatra': 'Chatra',
            'Chennai': 'Chennai',
            'Chhatarpur': 'Chhatarpur',
            'Chhindwara': 'Chhindwara',
            'Chikkaballapura': 'Chikballapur',
            'Chikkamagaluru': 'Chikkamagaluru',
            'Chirang': 'Chirang',
            'Chitradurga': 'Chitradurga',
            'Chitrakoot': 'Chitrakoot',
            'Chittoor': 'Chittoor',
            'Chittorgarh': 'Chittorgarh',
            'Churachandpur': 'Churachandpur',
            'Churu': 'Churu',
            'Coimbatore': 'Coimbatore',
            'Cooch Behar': 'Cooch Behar',
            'Cuddalore': 'Cuddalore',
            'Cuttack': 'Cuttack',
            'Dadra And Nagar Haveli': 'Dadra and Nagar Haveli',
            'Dahod': 'Dahod',
            'Dakshin Dinajpur': 'Dakshin Dinajpur',
            'Dakshina Kannada': 'Dakshina Kannada',
            'Daman': 'Daman',
            'Damoh': 'Damoh',
            'Dang': 'Dang',
            'Dantewada': 'Dantewada',
            'Darbhanga': 'Darbhanga',
            'Darjeeling': 'Darjeeling',
            'Darrang': 'Darrang',
            'Datia': 'Datia',
            'Dausa': 'Dausa',
            'Davangere': 'Davangere',
            'Debagarh': 'Deogarh',
            'Dehradun': 'Dehradun',
            'Deoghar': 'Deoghar',
            'Deoria': 'Deoria',
            'Dewas': 'Dewas',
            'Dhalai': 'Dhalai',
            'Dhamtari': 'Dhamtari',
            'Dhanbad': 'Dhanbad',
            'Dhar': 'Dhar',
            'Dharmapuri': 'Dharmapuri',
            'Dharwad': 'Dharwad',
            'Dhemaji': 'Dhemaji',
            'Dhenkanal': 'Dhenkanal',
            'Dholpur': 'Dholpur',
            'Dhubri': 'Dhubri',
            'Dhule': 'Dhule',
            'Dibang Valley': 'Dibang Valley',
            'Dibrugarh': 'Dibrugarh',
            'Dima Hasao': 'Dima Hasao',
            'Dimapur': 'Dimapur',
            'Dindigul': 'Dindigul',
            'Dindori': 'Dindori',
            'Diu': 'Diu',
            'Doda': 'Doda',
            'Dumka': 'Dumka',
            'Dungarpur': 'Dungarpur',
            'Durg': 'Durg',
            'East Champaran': 'East Champaran',
            'East Delhi': 'East Delhi',
            'East Garo Hills': 'East Garo Hills',
            'East Godavari': 'East Godavari',
            'East Jaintia Hills': 'East Jaintia Hills',
            'East Kameng': 'East Kameng',
            'East Khasi Hills': 'East Khasi Hills',
            'East Siang': 'East Siang',
            'East Sikkim': 'East Sikkim',
            'East Singhbhum': 'East Singhbhum',
            'Ernakulam': 'Ernakulam',
            'Erode': 'Erode',
            'Etah': 'Etah',
            'Etawah': 'Etawah',
            'Faizabad': 'Ayodhya',
            'Faridabad': 'Faridabad',
            'Faridkot': 'Faridkot',
            'Farrukhabad': 'Farrukhabad',
            'Fatehabad': 'Fatehabad',
            'Fatehgarh Sahib': 'Fatehgarh Sahib',
            'Fatehpur': 'Fatehpur',
            'Fazilka': 'Fazilka',
            'Firozabad': 'Firozabad',
            'Firozpur': 'Ferozepur',
            'Gadag': 'Gadag',
            'Gadchiroli': 'Gadchiroli',
            'Gajapati': 'Gajapati',
            'Ganderbal': 'Ganderbal',
            'Gandhinagar': 'Gandhinagar',
            'Ganganagar': 'Sri Ganganagar',
            'Ganjam': 'Ganjam',
            'Garhwa': 'Garhwa',
            'Gautam Buddha Nagar': 'Gautam Buddha Nagar',
            'Gaya': 'Gaya',
            'Ghaziabad': 'Ghaziabad',
            'Ghazipur': 'Ghazipur',
            'Gir Somnath': 'Gir Somnath',
            'Giridih': 'Giridih',
            'Goalpara': 'Goalpara',
            'Godda': 'Godda',
            'Golaghat': 'Golaghat',
            'Gomati': 'Gomati',
            'Gonda': 'Gonda',
            'Gondia': 'Gondia',
            'Gopalganj': 'Gopalganj',
            'Gorakhpur': 'Gorakhpur',
            'Gulbarga': 'Kalaburagi',
            'Gumla': 'Gumla',
            'Guna': 'Guna',
            'Guntur': 'Guntur',
            'Gurdaspur': 'Gurdaspur',
            'Gurgaon': 'Gurugram',
            'Gwalior': 'Gwalior',
            'Hailakandi': 'Hailakandi',
            'Hamirpur': 'Hamirpur',
            'Hanumangarh': 'Hanumangarh',
            'Harda': 'Harda',
            'Hardoi': 'Hardoi',
            'Haridwar': 'Haridwar',
            'Hassan': 'Hassan',
            'Hathras': 'Hathras',
            'Haveri': 'Haveri',
            'Hazaribagh': 'Hazaribagh',
            'Hingoli': 'Hingoli',
            'Hisar': 'Hisar',
            'Hooghly': 'Hooghly',
            'Hoshangabad': 'Hoshangabad',
            'Hoshiarpur': 'Hoshiarpur',
            'Howrah': 'Howrah',
            'Hyderabad': 'Hyderabad',
            'Idukki': 'Idukki',
            'Imphal East': 'Imphal East',
            'Imphal West': 'Imphal West',
            'Indore': 'Indore',
            'Jabalpur': 'Jabalpur',
            'Jagatsinghapur': 'Jagatsinghpur',
            'Jagtial': 'Jagtial',
            'Jaipur': 'Jaipur',
            'Jaisalmer': 'Jaisalmer',
            'Jajapur': 'Jajpur',
            'Jalandhar': 'Jalandhar',
            'Jalaun': 'Jalaun',
            'Jalgaon': 'Jalgaon',
            'Jalna': 'Jalna',
            'Jalpaiguri': 'Jalpaiguri',
            'Jammu': 'Jammu',
            'Jamnagar': 'Jamnagar',
            'Jamtara': 'Jamtara',
            'Jamui': 'Jamui',
            'Janjgir-Champa': 'Janjgir Champa',
            'Jashpur': 'Jashpur',
            'Jaunpur': 'Jaunpur',
            'Jehanabad': 'Jehanabad',
            'Jhabua': 'Jhabua',
            'Jhajjar': 'Jhajjar',
            'Jhalawar': 'Jhalawar',
            'Jhansi': 'Jhansi',
            'Jhargram': 'Jhargram',
            'Jharsuguda': 'Jharsuguda',
            'Jhunjhunu': 'Jhunjhunu',
            'Jind': 'Jind',
            'Jodhpur': 'Jodhpur',
            'Jorhat': 'Jorhat',
            'Junagadh': 'Junagadh',
            'Jyotiba Phule Nagar': 'Amroha',
            'Kabirdham': 'Kabirdham',
            'Kachchh': 'Kutch',
            'Kadapa': 'YSR District',
            'Kaimur': 'Kaimur',
            'Kaithal': 'Kaithal',
            'Kalahandi': 'Kalahandi',
            'Kamrup': 'Kamrup',
            'Kamrup Metropolitan': 'Kamrup Metropolitan',
            'Kanchipuram': 'Kanchipuram',
            'Kandhamal': 'Kandhamal',
            'Kangra': 'Kangra',
            'Kanker': 'Kanker',
            'Kannauj': 'Kannauj',
            'Kannur': 'Kannur',
            'Kanpur Dehat': 'Kanpur Dehat',
            'Kanpur Nagar': 'Kanpur Nagar',
            'Kanyakumari': 'Kanyakumari',
            'Kapurthala': 'Kapurthala',
            'Karaikal': 'Karaikal',
            'Karauli': 'Karauli',
            'Karbi Anglong': 'Karbi Anglong',
            'Kargil': 'Kargil',
            'Karimganj': 'Karimganj',
            'Karimnagar': 'Karimnagar',
            'Karnal': 'Karnal',
            'Karur': 'Karur',
            'Kasaragod': 'Kasaragod',
            'Kasganj': 'Kasganj',
            'Kathua': 'Kathua',
            'Katihar': 'Katihar',
            'Katni': 'Katni',
            'Kaushambi': 'Kaushambi',
            'Kendrapara': 'Kendrapara',
            'Kendujhar': 'Kendujhar',
            'Khagaria': 'Khagaria',
            'Khammam': 'Khammam',
            'Khandwa': 'Khandwa',
            'Khargone': 'Khargone',
            'Kheda': 'Kheda',
            'Kheri': 'Kheri',
            'Khordha': 'Khordha',
            'Khowai': 'Khowai',
            'Khunti': 'Khunti',
            'Kinnaur': 'Kinnaur',
            'Kiphire': 'Kiphire',
            'Kishanganj': 'Kishanganj',
            'Kishtwar': 'Kishtwar',
            'Kodagu': 'Kodagu',
            'Koderma': 'Koderma',
            'Kohima': 'Kohima',
            'Kokrajhar': 'Kokrajhar',
            'Kolar': 'Kolar',
            'Kolasib': 'Kolasib',
            'Kolhapur': 'Kolhapur',
            'Kollam': 'Kollam',
            'Koppal': 'Koppal',
            'Koraput': 'Koraput',
            'Korba': 'Korba',
            'Koriya': 'Koriya',
            'Kota': 'Kota',
            'Kottayam': 'Kottayam',
            'Kozhikode': 'Kozhikode',
            'Krishna': 'Krishna',
            'Krishnagiri': 'Krishnagiri',
            'Kulgam': 'Kulgam',
            'Kullu': 'Kullu',
            'Kupwara': 'Kupwara',
            'Kurnool': 'Kurnool',
            'Kurukshetra': 'Kurukshetra',
            'Kurung Kumey': 'Kurung Kumey',
            'Kushinagar': 'Kushinagar',
            'Kutch': 'Kutch',
            'Lahaul And Spiti': 'Lahaul and Spiti',
            'Lakhimpur': 'Lakhimpur',
            'Lakhisarai': 'Lakhisarai',
            'Lakshadweep': 'Lakshadweep',
            'Lalitpur': 'Lalitpur',
            'Latehar': 'Latehar',
            'Latur': 'Latur',
            'Lawngtlai': 'Lawngtlai',
            'Leh': 'Leh',
            'Lohardaga': 'Lohardaga',
            'Lohit': 'Lohit',
            'Longleng': 'Longleng',
            'Lucknow': 'Lucknow',
            'Ludhiana': 'Ludhiana',
            'Lunglei': 'Lunglei',
            'Madhepura': 'Madhepura',
            'Madhubani': 'Madhubani',
            'Madurai': 'Madurai',
            'Mahabubnagar': 'Mahabubnagar',
            'Maharajganj': 'Maharajganj',
            'Mahasamund': 'Mahasamund',
            'Mahe': 'Mahe',
            'Mahendragarh': 'Mahendragarh',
            'Mahisagar': 'Mahisagar',
            'Mahoba': 'Mahoba',
            'Mainpuri': 'Mainpuri',
            'Malappuram': 'Malappuram',
            'Malda': 'Malda',
            'Malkangiri': 'Malkangiri',
            'Mamit': 'Mamit',
            'Mandi': 'Mandi',
            'Mandla': 'Mandla',
            'Mandsaur': 'Mandsaur',
            'Mandya': 'Mandya',
            'Mansa': 'Mansa',
            'Marigaon': 'Morigaon',
            'Mathura': 'Mathura',
            'Mau': 'Mau',
            'Mayurbhanj': 'Mayurbhanj',
            'Medak': 'Medak',
            'Meerut': 'Meerut',
            'Mehsana': 'Mehsana',
            'Mewat': 'Nuh',
            'Mirzapur': 'Mirzapur',
            'Moga': 'Moga',
            'Mokokchung': 'Mokokchung',
            'Mon': 'Mon',
            'Moradabad': 'Moradabad',
            'Morena': 'Morena',
            'Muktsar': 'Sri Muktsar Sahib',
            'Mumbai': 'Mumbai City',
            'Mumbai Suburban': 'Mumbai Suburban',
            'Mungeli': 'Mungeli',
            'Munger': 'Munger',
            'Murshidabad': 'Murshidabad',
            'Muzaffarnagar': 'Muzaffarnagar',
            'Muzaffarpur': 'Muzaffarpur',
            'Mysore': 'Mysuru',
            'Nabarangapur': 'Nabarangpur',
            'Nabarangpur': 'Nabarangpur',
            'Nadia': 'Nadia',
            'Nagaon': 'Nagaon',
            'Nagapattinam': 'Nagapattinam',
            'Nagaur': 'Nagaur',
            'Nagpur': 'Nagpur',
            'Nainital': 'Nainital',
            'Nalanda': 'Nalanda',
            'Nalbari': 'Nalbari',
            'Nalgonda': 'Nalgonda',
            'Namakkal': 'Namakkal',
            'Nanded': 'Nanded',
            'Nandurbar': 'Nandurbar',
            'Narayanpur': 'Narayanpur',
            'Narmada': 'Narmada',
            'Narsinghpur': 'Narsinghpur',
            'Nashik': 'Nashik',
            'Nasik': 'Nashik',
            'Navsari': 'Navsari',
            'Nawada': 'Nawada',
            'Nawanshahr': 'Shaheed Bhagat Singh Nagar',
            'Nayagarh': 'Nayagarh',
            'Neemuch': 'Neemuch',
            'Nicobar': 'Nicobar',
            'Nizamabad': 'Nizamabad',
            'North 24 Parganas': 'North 24 Parganas',
            'North And Middle Andaman': 'North and Middle Andaman',
            'North Delhi': 'North Delhi',
            'North East Delhi': 'North East Delhi',
            'North Garo Hills': 'North Garo Hills',
            'North Goa': 'North Goa',
            'North Sikkim': 'North Sikkim',
            'North Tripura': 'North Tripura',
            'North West Delhi': 'North West Delhi',
            'Nuapada': 'Nuapada',
            'Osmanabad': 'Osmanabad',
            'Pakur': 'Pakur',
            'Palakkad': 'Palakkad',
            'Palamu': 'Palamu',
            'Palghar': 'Palghar',
            'Pali': 'Pali',
            'Palwal': 'Palwal',
            'Panch Mahals': 'Panchmahal',
            'Panchkula': 'Panchkula',
            'Panipat': 'Panipat',
            'Panna': 'Panna',
            'Papum Pare': 'Papum Pare',
            'Parbhani': 'Parbhani',
            'Paschim Bardhaman': 'Paschim Bardhaman',
            'Paschim Medinipur': 'Paschim Medinipur',
            'Pashchim Champaran': 'West Champaran',
            'Pashchimi Singhbhum': 'West Singhbhum',
            'Patan': 'Patan',
            'Pathanamthitta': 'Pathanamthitta',
            'Pathankot': 'Pathankot',
            'Patiala': 'Patiala',
            'Patna': 'Patna',
            'Pattanamtitta': 'Pathanamthitta',
            'Pauri Garhwal': 'Pauri Garhwal',
            'Perambalur': 'Perambalur',
            'Peren': 'Peren',
            'Phek': 'Phek',
            'Pilibhit': 'Pilibhit',
            'Pithoragarh': 'Pithoragarh',
            'Poonch': 'Poonch',
            'Porbandar': 'Porbandar',
            'Prakasam': 'Prakasam',
            'Pratapgarh': 'Pratapgarh',
            'Puducherry': 'Puducherry',
            'Pulwama': 'Pulwama',
            'Pune': 'Pune',
            'Purba Bardhaman': 'Purba Bardhaman',
            'Purba Champaran': 'East Champaran',
            'Purba Medinipur': 'Purba Medinipur',
            'Puri': 'Puri',
            'Purnia': 'Purnia',
            'Purulia': 'Purulia',
            'Puruliya': 'Purulia',
            'Rae Bareli': 'Raebareli',
            'Raebareli': 'Raebareli',
            'Raichur': 'Raichur',
            'Raigad': 'Raigad',
            'Raigarh': 'Raigarh',
            'Raipur': 'Raipur',
            'Raisen': 'Raisen',
            'Rajauri': 'Rajouri',
            'Rajgarh': 'Rajgarh',
            'Rajkot': 'Rajkot',
            'Rajnandgaon': 'Rajnandgaon',
            'Rajouri': 'Rajouri',
            'Rajsamand': 'Rajsamand',
            'Ramanagara': 'Ramanagara',
            'Ramanathapuram': 'Ramanathapuram',
            'Ramban': 'Ramban',
            'Ramgarh': 'Ramgarh',
            'Rampur': 'Rampur',
            'Ranchi': 'Ranchi',
            'Ranga Reddy': 'Ranga Reddy',
            'Rangareddy': 'Ranga Reddy',
            'Ratlam': 'Ratlam',
            'Ratnagiri': 'Ratnagiri',
            'Rayagada': 'Rayagada',
            'Reasi': 'Reasi',
            'Rewa': 'Rewa',
            'Rewari': 'Rewari',
            'Ri Bhoi': 'Ri-Bhoi',
            'Rohtak': 'Rohtak',
            'Rohtas': 'Rohtas',
            'Rudraprayag': 'Rudraprayag',
            'Rupnagar': 'Rupnagar',
            'S.A.S Nagar': 'SAS Nagar',
            'Sabarkantha': 'Sabarkantha',
            'Sagar': 'Sagar',
            'Saharanpur': 'Saharanpur',
            'Saharsa': 'Saharsa',
            'Sahibganj': 'Sahibganj',
            'Sahibzada Ajit Singh Nagar': 'SAS Nagar',
            'Saiha': 'Saiha',
            'Salem': 'Salem',
            'Samastipur': 'Samastipur',
            'Samba': 'Samba',
            'Sambalpur': 'Sambalpur',
            'Sambhal': 'Sambhal',
            'Sangli': 'Sangli',
            'Sangrur': 'Sangrur',
            'Sant Kabir Nagar': 'Sant Kabir Nagar',
            'Sant Ravidas Nagar': 'Bhadohi',
            'Saran': 'Saran',
            'Satara': 'Satara',
            'Satna': 'Satna',
            'Sawai Madhopur': 'Sawai Madhopur',
            'Sehore': 'Sehore',
            'Senapati': 'Senapati',
            'Seoni': 'Seoni',
            'Sepahijala': 'Sepahijala',
            'Seraikela Kharsawan': 'Seraikela-Kharsawan',
            'Serchhip': 'Serchhip',
            'Shahdol': 'Shahdol',
            'Shaheed Bhagat Singh Nagar': 'Shaheed Bhagat Singh Nagar',
            'Shahid Bhagat Singh Nagar': 'Shaheed Bhagat Singh Nagar',
            'Shahjahanpur': 'Shahjahanpur',
            'Shajapur': 'Shajapur',
            'Shamli': 'Shamli',
            'Sheikhpura': 'Sheikhpura',
            'Sheohar': 'Sheohar',
            'Sheopur': 'Sheopur',
            'Shimla': 'Shimla',
            'Shimoga': 'Shivamogga',
            'Shivpuri': 'Shivpuri',
            'Shopian': 'Shopian',
            'Shravasti': 'Shravasti',
            'Shupiyan': 'Shopian',
            'Siddharth Nagar': 'Siddharthnagar',
            'Siddharthnagar': 'Siddharthnagar',
            'Sidhi': 'Sidhi',
            'Sikar': 'Sikar',
            'Simdega': 'Simdega',
            'Sindhudurg': 'Sindhudurg',
            'Singrauli': 'Singrauli',
            'Sipahijala': 'Sepahijala',
            'Sirmaur': 'Sirmaur',
            'Sirohi': 'Sirohi',
            'Sirsa': 'Sirsa',
            'Sitamarhi': 'Sitamarhi',
            'Sitapur': 'Sitapur',
            'Sivaganga': 'Sivaganga',
            'Sivasagar': 'Sivasagar',
            'Siwan': 'Siwan',
            'Solan': 'Solan',
            'Solapur': 'Solapur',
            'Sonapur': 'Subarnapur',
            'Sonbhadra': 'Sonbhadra',
            'Sonipat': 'Sonipat',
            'Sonitpur': 'Sonitpur',
            'South 24 Parganas': 'South 24 Parganas',
            'South Andaman': 'South Andaman',
            'South Delhi': 'South Delhi',
            'South East Delhi': 'South East Delhi',
            'South Garo Hills': 'South Garo Hills',
            'South Goa': 'South Goa',
            'South Sikkim': 'South Sikkim',
            'South Tripura': 'South Tripura',
            'South West Delhi': 'South West Delhi',
            'South West Garo Hills': 'South West Garo Hills',
            'South West Khasi Hills': 'South West Khasi Hills',
            'Sri Ganganagar': 'Sri Ganganagar',
            'Sri Muktsar Sahib': 'Sri Muktsar Sahib',
            'Srikakulam': 'Srikakulam',
            'Srinagar': 'Srinagar',
            'Subarnapur': 'Subarnapur',
            'Sukma': 'Sukma',
            'Sultanpur': 'Sultanpur',
            'Sundargarh': 'Sundargarh',
            'Supaul': 'Supaul',
            'Surajpur': 'Surajpur',
            'Surat': 'Surat',
            'Surendranagar': 'Surendranagar',
            'Surguja': 'Surguja',
            'Tamenglong': 'Tamenglong',
            'Tapi': 'Tapi',
            'Tarn Taran': 'Tarn Taran',
            'Tawang': 'Tawang',
            'Tehri Garhwal': 'Tehri Garhwal',
            'Thane': 'Thane',
            'Thanjavur': 'Thanjavur',
            'The Dangs': 'Dang',
            'Theni': 'Theni',
            'Thiruvallur': 'Tiruvallur',
            'Thiruvananthapuram': 'Thiruvananthapuram',
            'Thoothukkudi': 'Thoothukudi',
            'Thoubal': 'Thoubal',
            'Thrissur': 'Thrissur',
            'Tikamgarh': 'Tikamgarh',
            'Tinsukia': 'Tinsukia',
            'Tirap': 'Tirap',
            'Tiruchirappalli': 'Tiruchirappalli',
            'Tirunelveli': 'Tirunelveli',
            'Tiruppur': 'Tiruppur',
            'Tiruvallur': 'Tiruvallur',
            'Tiruvannamalai': 'Tiruvannamalai',
            'Tiruvarur': 'Tiruvarur',
            'Tonk': 'Tonk',
            'Tuensang': 'Tuensang',
            'Tumakuru': 'Tumakuru',
            'Tumkur': 'Tumakuru',
            'Udaipur': 'Udaipur',
            'Udalguri': 'Udalguri',
            'Udham Singh Nagar': 'Udham Singh Nagar',
            'Udhampur': 'Udhampur',
            'Udhamsingh Nagar': 'Udham Singh Nagar',
            'Udupi': 'Udupi',
            'Ujjain': 'Ujjain',
            'Ukhrul': 'Ukhrul',
            'Umaria': 'Umaria',
            'Una': 'Una',
            'Unakoti': 'Unakoti',
            'Unnao': 'Unnao',
            'Upper Siang': 'Upper Siang',
            'Upper Subansiri': 'Upper Subansiri',
            'Uttar Bastar Kanker': 'Kanker',
            'Uttar Dinajpur': 'Uttar Dinajpur',
            'Uttar Kashi': 'Uttarkashi',
            'Uttara Kannada': 'Uttara Kannada',
            'Uttarkashi': 'Uttarkashi',
            'Vadodara': 'Vadodara',
            'Vaishali': 'Vaishali',
            'Valsad': 'Valsad',
            'Varanasi': 'Varanasi',
            'Vellore': 'Vellore',
            'Vidisha': 'Vidisha',
            'Vijayapura': 'Vijayapura',
            'Vikarabad': 'Vikarabad',
            'Villupuram': 'Villupuram',
            'Viluppuram': 'Villupuram',
            'Virudhunagar': 'Virudhunagar',
            'Visakhapatnam': 'Visakhapatnam',
            'Vizianagaram': 'Vizianagaram',
            'Warangal': 'Warangal', 
            'Warangal Urban': 'Warangal',
            'Warangal Rural': 'Warangal',
            'Wardha': 'Wardha',
            'Washim': 'Washim',
            'Wayanad': 'Wayanad',
            'West Champaran': 'West Champaran',
            'West Delhi': 'West Delhi',
            'West Garo Hills': 'West Garo Hills',
            'West Godavari': 'West Godavari',
            'West Jaintia Hills': 'West Jaintia Hills',
            'West Kameng': 'West Kameng',
            'West Khasi Hills': 'West Khasi Hills',
            'West Siang': 'West Siang',
            'West Sikkim': 'West Sikkim',
            'West Singhbhum': 'West Singhbhum',
            'West Tripura': 'West Tripura',
            'Wokha': 'Wokha',
            'Y.S.R.': 'YSR District',
            'Yadgir': 'Yadgir',
            'Yamunanagar': 'Yamunanagar',
            'Yanam': 'Yanam',
            'Yavatmal': 'Yavatmal',
            'Ysr': 'YSR District',
            'Zunheboto': 'Zunheboto'
        }
        data['district'] = data['district'].replace(district_corrections)

    unique_districts = sorted(data['district'].unique())
    with open("locations_output.txt", "w", encoding="utf-8") as f:
        f.write("\n[VALID DISTRICTS]\n")
        for d in unique_districts:
            f.write(f"|{d}|\n")
    print("Done. Wrote to locations_output.txt")

if __name__ == "__main__":
    check_locations()
